#!/bin/sh

# To enable apc tests, add the "apc" tag to hosts.cfg.

$XYMONHOME/bin/xymongrep --noextras "apc" | while read ip host hash line; do
    output=$(/sbin/apcaccess)
    res=$?

    status=$(echo "$output" | grep STATUS | cut -d: -f2 | sed -r 's/^\s+|\s+$//g')

    color='red'
    if [ "$status" = 'ONLINE' ]; then
        color='green'
    fi

    # send status
    ( echo "status $host.apc $color $(LANG=C date) $status"
      echo
      echo "$output"
    ) | $XYMON $XYMSRV @

    # extract temperature info if available and send to trends
    temp=$(echo "$output" | grep ITEMP | awk '{print $3}')
    if test -n "$temp"; then
      ( echo "data $host.trends"
        echo "[temp,internal.rrd]"
        echo "DS:temp:GAUGE:600:U:U $temp"
      ) | $XYMON $XYMSRV @
    fi
done
