#!/bin/sh
# explicitly list interesting subtrees to avoid problems like:
# Error: OID not increasing: IJXXXX-MIB::net-peripheral.3.1 
oids="
IJXXXX-MIB::consumable-pages-printed-with-supply
IJXXXX-MIB::consumables-life
IJXXXX-MIB::duplex-page-count
IJXXXX-MIB::energy-star
IJXXXX-MIB::pcl-total-page-count
IJXXXX-MIB::postscript-total-page-count
IJXXXX-MIB::scanner-accessory-total-copy-pages-printed
HP-LASERJET-COMMON-MIB::total-engine-page-count
IJXXXX-MIB::total-mono-page-count"

# To enable hpprinter tests, add the "hpprinter" tag to hosts.cfg.
$XYMONHOME/bin/xymongrep --noextras "hpprinter" | while read ip host hash line; do
    color='clear'

    output=$(echo "$oids" | xargs -i sh -c "snmpwalk -v1 -cpublic printer01 {} || exit 255" 2>&1)
    res=$?

    if [ $res -eq 0 ]; then
        output=$(echo "$output" | grep INTEGER | cut -d: -f3- | sed -r 's/.0\s*=\s*INTEGER//' | sort -u)
        # TODO: tresholds and colors?
        color='green'
    else
        color='red'
    fi

    # send status
    ( echo "status $host.printer $color `date`"
      echo
      echo "$output"
    ) | $XYMON $XYMSRV @
done

