#!/usr/bin/env python
# -*- coding: utf-8 -*-
# To enable opnsense tests, add the "opnsense" tag to hosts.cfg. place password in opnsensepasswd file in $XYMONHOME directory
import os
import logging
import subprocess
import requests
from bs4 import BeautifulSoup
import Hobbit
from xymon_utils import cache as xymon_cache

logging.basicConfig()
logger = logging.getLogger()
#logger.setLevel(logging.DEBUG)

username = 'status'
passwordfile = os.path.join(os.environ.get('XYMONHOME', '/usr/lib/xymon/server'), 'etc', 'opnsensepasswd')

def get_password(host, username, passfile):
    with open(passfile) as f:
        for line in f.read().splitlines():
            parts = line.split(':')
            if parts[0:2] == [host, username]:
                return parts[2:5]
    return ()

@xymon_cache('fwstatus', 3600)
def firmware_status(host, api):
    r = api.get('https://%s/api/core/firmware/status' % host)
    if r.status_code != 200:
        return None

    return r.json()

def web_auth(wapi, host, username, password):
    # fetch index to get CSRF token
    r = wapi.get('https://%s/' % host)
    if r.status_code != 200:
        return False

    soup = BeautifulSoup(r.text, 'lxml')

    token=soup.find('input', type='hidden')

    # login
    r = wapi.post(
        'https://%s/' % host,
        data={
            'login': 1,
            'passwordfld': password,
            'usernamefld': username,
            token['name']: token['value']
        }
    )
    if r.status_code != 200:
        return False

    return True

def check_updates(host, api):

    fwstatus = firmware_status(host, api)

    bb = Hobbit.Hobbit(test='opn', hostname=host)
    if fwstatus is None:
        bb.color_line('red', 'Error reading firmware status (code: %d)' % r.status_code)
        bb.send()
        return

    if 'There are no updates available' in fwstatus['status_msg']:
        bb.add_color('green')
    else:
        bb.add_color('red')

    bb.lineprint(fwstatus['status_msg'])

    bb.lineprint("Last check: %s" % fwstatus['last_check'])

    bb.send()

def percent_used(data, usedname='used', totalname='total'):
    return 100. * float(data[usedname]) / float(data[totalname])

def size_to_bytes(value):
    unit = value[-1]
    value = float(value[:-1])
    if unit == 'T':
        return value * 1024 * 1024 * 1024 * 1024
    if unit == 'G':
        return value * 1024 * 1024 * 1024
    if unit == 'M':
        return value * 1024 * 1024
    if unit == 'K':
        return value * 1024

def monitor_firewall(ip, host):
    (password, key, secret) = get_password(host, username, passwordfile)

    api = requests.session()
    api.auth = (key, secret)

    check_updates(host, api)

    wapi = requests.session()
    if not web_auth(wapi, host, username, password):
        print('ERROR: web_auth failed.')
        return

    r = wapi.get('https://%s/widgets/api/get.php' % host, params={'load': ','.join(['system', 'interfaces', 'gateway', 'temperature'])})
    if r.status_code != 200:
        return None

    wdata = r.json()['data']

    trends = Hobbit.trends(hostname=host)
    client = Hobbit.Hobbit(test='freebsd', type='client', hostname=host.replace('.', ','));

    client.lineprint('[osversion]')
    for line in wdata['system']['versions']:
        client.lineprint(line)
    client.lineprint('[date]')
    client.lineprint(wdata['system']['date_frmt'])

    trends.lineprint("[la.rrd]")
    trends.lineprint("DS:la:GAUGE:600:U:U %g" % (100. * float(wdata['system']['cpu']['load'][1])))

    trends.lineprint("[vmstat.rrd]")
    trends.lineprint("DS:cpu_sys:GAUGE:600:0:U %g" % float(wdata['system']['cpu']['sys']))
    trends.lineprint("DS:cpu_usr:GAUGE:600:0:U %g" % (float(wdata['system']['cpu']['user'])+float(wdata['system']['cpu']['nice'])))
    trends.lineprint("DS:cpu_idl:GAUGE:600:0:U %g" % float(wdata['system']['cpu']['idle']))
    trends.lineprint("DS:cpu_int:GAUGE:600:0:U %g" % float(wdata['system']['cpu']['intr']))
    trends.lineprint("DS:cpu_wait:GAUGE:600:0:U U")

    trends.lineprint("[memory.actual.rrd]")
    trends.lineprint("DS:realmempct:GAUGE:600:0:U %g" % percent_used(wdata['system']['kernel']['memory']))
    trends.lineprint("[memory.real.rrd]")
    trends.lineprint("DS:realmempct:GAUGE:600:0:U U")
    trends.lineprint("[memory.swap.rrd]")
    if wdata['system']['disk']['swap']['total'] != '':
        trends.lineprint("DS:realmempct:GAUGE:600:0:U %g" % percent_used(wdata['system']['disk']['swap']))
    else:
        trends.lineprint("DS:realmempct:GAUGE:600:0:U U")

    trends.lineprint("[states.rrd]")
    trends.lineprint("DS:used:GAUGE:600:U:U %d" % int(wdata['system']['kernel']['pf']['states']))
    trends.lineprint("DS:max:GAUGE:600:U:U %d" % int(wdata['system']['kernel']['pf']['maxstates']))
    trends.lineprint("DS:usedpct:GAUGE:600:U:U %g" % percent_used(wdata['system']['kernel']['pf'], 'states', 'maxstates'))

    trends.lineprint("[mbuf.rrd]")
    trends.lineprint("DS:used:GAUGE:600:U:U %d" % int(wdata['system']['kernel']['mbuf']['total']))
    trends.lineprint("DS:max:GAUGE:600:U:U %d" % int(wdata['system']['kernel']['mbuf']['max']))
    trends.lineprint("DS:usedpct:GAUGE:600:U:U %g" % percent_used(wdata['system']['kernel']['mbuf'], 'total', 'max'))

    for disk in wdata['system']['disk']['devices']:
        name = disk['mountpoint'][1:] or 'root'
        size = size_to_bytes(disk['size'])
        used = size_to_bytes(disk['used'])
        trends.lineprint("[disk,%s.rrd]" % name)
        trends.lineprint("DS:pct:GAUGE:600:0:100 %g" % (100. * used / size))
        trends.lineprint("DS:used:GAUGE:600:0:U %g" % used)

    for iface in wdata['interfaces']:
        trends.lineprint("[ifstat,%s.rrd]" % iface['name'])
        trends.lineprint("DS:bytesReceived:DERIVE:600:0:U %d" % int(iface['inbytes']))
        trends.lineprint("DS:bytesSent:DERIVE:600:0:U %d" % int(iface['outbytes']))

    for temp in wdata['temperature']:
        trends.lineprint("[temp,%s.rrd]" % temp['device'].replace('.', '_'))
        trends.lineprint("DS:temp:GAUGE:600:U:U %g" % float(temp['temperature']))

    trends.send()
    client.send()

hosts = subprocess.Popen('xymongrep --noextras opnsense', shell=True, stdout=subprocess.PIPE)
for line in hosts.stdout:
    ip, host = line.split(' ')[:2]
    monitor_firewall(ip, host)
